services:
  aniv:
    build: .
    container_name: aniv
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_PATH: /app/data/aniv.sqlite
    volumes:
      - ./content:/app/content:ro
      - ./images:/app/images
      - ./public:/app/public:ro
      - aniv-data:/app/data
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: aniv-ngrok
    command: http aniv:3000
    environment:
      NGROK_AUTHTOKEN: 2RVYz7IoxvGWS42Rf8Nnd2ycW1x_53KFB92HSYvZfgeNAoKmy
    depends_on:
      - aniv
    restart: unless-stopped

volumes:
  aniv-data: