import express from 'express';
import path from 'node:path';
import fs from 'node:fs';
import { ROOT, DB_PATH, driver } from './db.js';
import { seed } from './seed.js';
import api from './routes/api.js';

const app = express();
const PORT = process.env.PORT || 3000;

app.disable('x-powered-by');
app.use(express.json({ limit: '256kb' }));

// Content JSON is the source of truth — mirror it into the DB on every boot.
seed();

app.use('/api', api);

// Photos live in /images at the project root: that's the drop-in folder.
// _web and _thumb are generated by `npm run images`.
app.use('/images', express.static(path.join(ROOT, 'images'), {
  maxAge: '7d',
  setHeaders: (res) => res.setHeader('Cache-Control', 'public, max-age=604800'),
}));

app.use(express.static(path.join(ROOT, 'public'), { extensions: ['html'] }));

app.get('*', (_req, res) => res.sendFile(path.join(ROOT, 'public', 'index.html')));

app.use((err, _req, res, _next) => {
  console.error('[error]', err);
  res.status(500).json({ ok: false, error: 'server error' });
});

if (!process.env.VERCEL) {
  app.listen(PORT, '0.0.0.0', () => {
    const photos = fs.existsSync(path.join(ROOT, 'images')) ? fs.readdirSync(path.join(ROOT, 'images')).filter((f) => !f.startsWith('_')).length : 0;
    console.log('');
    console.log('  ╭───────────────────────────────────────────────╮');
    console.log('  │  Aniv — Marco & Aby                           │');
    console.log('  ╰───────────────────────────────────────────────╯');
    console.log(`   listening   http://localhost:${PORT}`);
    console.log(`   storage     ${driver}${driver === 'sqlite' ? ` (${DB_PATH})` : ''}`);
    console.log(`   photos      ${photos} in /images`);
    console.log('');
  });
}

export default app;
